[22012] Update migration guide removing things not related to application developer
eProsima/Fast-DDS-docs pull request #1003
Opened 2024-12-24 10:52 UTC by juanjo4936

## Description

WIP: Modify the migration guide from Fast 2 to Fast 3. Eliminated some lines that referred to private files or internal tasks, and clarified a few points. Found many additional changes that might be necessary so I'm opening the pull request to discuss the extra changes. 

@Mergifyio backport 3.1.x 3.0.x

## Contributor Checklist

- [ ] Commit messages follow the project guidelines. 
- [ ] Code snippets related to the added documentation have been provided.
- [ ] Documentation tests pass locally.
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] CI passes without warnings or errors.

2024-12-24 14:26 UTC, juanjo4936 commented on docs/notes/migration_guide.rst
> +   .. TODO:: Fix this table, ``fastdds/rtps/DomainParticipantQos.hpp`` has wrong path and doesn't include the content.
This file is not in this path, and doesn't match the content. I think maybe DomainParticipantExtendedQos.hpp?

2024-12-24 14:30 UTC, juanjo4936 commented on docs/notes/migration_guide.rst
> +
I believe this is way too brief. Shouldn't we explain what they should include instead?

2024-12-24 14:33 UTC, juanjo4936 commented on docs/notes/migration_guide.rst
> +
I have doubts the section itself is necessary. In any case, what would a user look for here? They would be trying to update the previous version I imagine, so the changes we made are not as important, right? I would imagine something like what Juan suggested, mention which examples in v2 became what examples in v3, to maintain their function. Note that it doesn't seem straightforward to me at all, given their naming changes.

2025-01-08 11:20 UTC, juanjo4936 commented on docs/notes/migration_guide.rst
> +        - ``fastdds/dds/domain/qos/DomainParticipantExtendedQos.hpp``
The code in this file is still slightly different

2025-01-09 06:57 UTC, rsanchez15 requested changes

2025-01-09 06:57 UTC, rsanchez15 commented on docs/notes/migration_guide.rst
> +        - ``fastdds/dds/domain/qos/DomainParticipantExtendedQos.hpp``
The extended QoS just adds the DDS Domain to the QoS, so I assume that the old RTPS Attributes were not migrated to the extended QoS but to the normal QoS. Please @Mario-DL verify this assumption.

2025-01-09 06:57 UTC, rsanchez15 commented on docs/notes/migration_guide.rst
> +consider the example `Configuration <https://github.com/eProsima/Fast-DDS/tree/master/examples/cpp/configuration>`_.
```suggestion
All examples in the Fast DDS project have been refactored to follow a consistent structure, having renamed files,
restructured classes, and updated the overall format. If you have integrated any example into your
own implementation, carefully review the updated examples to ensure compatibility with your project. As reference,
consider the example `Configuration <https://github.com/eProsima/Fast-DDS/tree/master/examples/cpp/configuration>`_.
```

Just removed some duplicated information

2025-01-09 07:37 UTC, juanjo4936 commented on docs/notes/migration_guide.rst
> +        - ``fastdds/dds/domain/qos/DomainParticipantExtendedQos.hpp``
The domain was moved to ExtendedQoS, it seems

2025-01-10 07:01 UTC, rsanchez15 approved these changes

2025-01-10 07:01 UTC, merged

2025-01-16 07:45 UTC, juanjo4936 commented
https://github.com/Mergifyio backport 3.1.x 3.0.x