Windows installation: remove dependencies
eProsima/Fast-DDS-docs pull request #232
Opened 2021-02-04 08:40 UTC by richiware

Described dependencies for Windows binaries installation are not necessary. This PR removes them.

2021-02-04 08:57 UTC, MiguelCompany requested changes
Please fix DCO

2021-02-05 08:02 UTC, jparisu requested changes

2021-02-05 08:02 UTC, jparisu commented on docs/installation/binaries/binaries_windows.rst
> -.. _install_bw:
Do not remove this tag

2021-02-05 08:09 UTC, richiware commented on docs/installation/binaries/binaries_windows.rst
> -.. _install_bw:
Done

2021-02-05 08:14 UTC, jparisu submitted a review, later dismissed
LGTM
Please fix DCO

2021-02-05 10:36 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=737)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/737/)

2021-02-08 08:27 UTC, rsanchez15 requested changes
Sign last commit

2021-02-09 08:11 UTC, richiware commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=741)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/741/)

2021-02-09 09:35 UTC, rsanchez15 approved these changes
LGTM

2021-02-09 10:14 UTC, merged