Multicast configuration on readers.
eProsima/Fast-DDS-docs pull request #233
Opened 2021-02-22 08:40 UTC by MiguelCompany

2021-02-22 11:11 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=743)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/743/)

2021-02-23 15:31 UTC, richiware requested changes

2021-02-23 15:31 UTC, richiware commented on code/XMLTester.xml
> +    <subscriber profile_name="publisher_xml_conf_multicast_locators_profile">
```suggestion
    <subscriber profile_name="subscriber_xml_conf_multicast_locators_profile">
```

2021-02-23 15:31 UTC, richiware commented on code/XMLTester.xml
> +    <subscriber profile_name="publisher_xml_conf_multicast_locators_profile">
If you decided to apply this suggestion, this profile name sure is used in the testing XML source code and you will change that too.

2021-02-24 06:52 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=745)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/745/)

2021-03-05 11:54 UTC, EduPonz commented
@richiprosima please test this

2021-03-05 11:58 UTC, EduPonz approved these changes
LGTM with green CI

2021-03-05 12:28 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=779)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/779/)

2021-03-05 12:42 UTC, merged