Add warning to domainId maximum
eProsima/Fast-DDS-docs pull request #234
Opened 2021-02-23 10:24 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2021-02-23 10:49 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=744)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/744/)

2021-03-05 11:51 UTC, EduPonz requested changes

2021-03-05 11:51 UTC, EduPonz commented on docs/fastdds/dds_layer/domain/domainParticipant/createDomainParticipant.rst
> +   Thus, it is encouraged to use domainIds lower than 200
Either use an alias or a literal for `domainId`.

2021-03-05 12:25 UTC, EduPonz approved these changes
LGTM with green CI

2021-03-05 12:39 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=780)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/780/)

2021-03-05 12:42 UTC, merged