Unique network flows
eProsima/Fast-DDS-docs pull request #235
Opened 2021-02-24 15:01 UTC by MiguelCompany

Adding documentation on the Unique Network flows use case.

2021-02-24 15:19 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=746)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/746/)

2021-02-24 16:27 UTC, EduPonz requested changes
In general, all the description is very readable and understandable. However, I'd appreciate some code snippets using the feature. Not only will it help readers, but the code will also be verified. This way, the use-case would be more in accordance with the rest of them,

2021-02-24 16:27 UTC, EduPonz commented on docs/fastdds/use_cases/use_cases.rst
> +  are explained here.
Although the sentence is completely correct, I'd go for something more direct (not accounting for line length):
```suggestion
  This use case illustrates the APIs that allow for the request of unique network flows, and for the identification of those in use.
```

2021-02-24 16:27 UTC, EduPonz commented on docs/fastdds/use_cases/unique_netwotk_flows/unique_netwotk_flows.rst
> +Ethernet, WiFi, 4G/5G telecommunication all rely on IP networking.
```suggestion
Ethernet, WiFi, 4G/5G telecommunication, all of them rely on IP networking.
```

2021-02-24 16:27 UTC, EduPonz commented on docs/fastdds/use_cases/unique_netwotk_flows/unique_netwotk_flows.rst
> +Such equipments are typically supporting 3GPP/5QI protocols to assign certain Network QoS parameters to
Is it tipically or is it more may support?
```suggestion
Such pieces of equipment typically support 3GPP/5QI protocols to assign certain Network QoS parameters to
```

2021-02-24 16:27 UTC, EduPonz commented on docs/fastdds/use_cases/unique_netwotk_flows/unique_netwotk_flows.rst
> +
```suggestion
```

2021-02-24 16:27 UTC, EduPonz commented on docs/fastdds/use_cases/unique_netwotk_flows/unique_netwotk_flows.rst
> +This means an application should be able to
```suggestion
This means an application should be able to:
```

2021-02-24 16:27 UTC, EduPonz commented on docs/fastdds/use_cases/unique_netwotk_flows/unique_netwotk_flows.rst
> +  - internet address
```suggestion
  - Transport protocol: UDP or TCP
  - Source port
  - Internet protocol: IPv4 or IPv6
  - IP address
```

2021-02-24 16:27 UTC, EduPonz commented on docs/fastdds/use_cases/unique_netwotk_flows/unique_netwotk_flows.rst
> +In other words, each network flow has two NFEs; one for the DataWriter and the other for the DataReader.
```suggestion
In other words, each network flow has two NFEs; one for the DataWriter, and the other for the DataReader.
```

2021-02-24 16:27 UTC, EduPonz commented on docs/fastdds/use_cases/unique_netwotk_flows/unique_netwotk_flows.rst
> +Fast DDS provides the APIs needed to get the list of NFEs used by a DataWriter or a DataReader.
```suggestion
Fast DDS provides the APIs needed to get the list of NFEs used by a given DataWriter or a DataReader.
```

2021-02-24 16:27 UTC, EduPonz commented on docs/fastdds/use_cases/unique_netwotk_flows/unique_netwotk_flows.rst
> +on wich the reader is listening.
Maybe we can put this into a list

2021-02-24 16:27 UTC, EduPonz commented on docs/fastdds/use_cases/unique_netwotk_flows/unique_netwotk_flows.rst
> +A unique flow can be created just ensuring that one of the two NFEs are unique.
```suggestion
A unique flow can be created by ensuring that at least one of the two NFEs are unique.
```

2021-02-24 16:27 UTC, EduPonz commented on docs/fastdds/use_cases/unique_netwotk_flows/unique_netwotk_flows.rst
> +On Fast DDS, there are two ways to select unique listening locators on the DataReader.
```suggestion
On Fast DDS, there are two ways to select unique listening locators on the DataReader:
```

2021-02-24 16:27 UTC, EduPonz commented on docs/fastdds/use_cases/unique_netwotk_flows/unique_netwotk_flows.rst
> +* The application can specify on which locators the DataReader should be listening, using :ref:`rtpsendpointqos` on
```suggestion
* The application can specify on which locators the DataReader should be listening. This is done using :ref:`rtpsendpointqos` on
```

2021-02-24 16:27 UTC, EduPonz commented on docs/fastdds/use_cases/unique_netwotk_flows/unique_netwotk_flows.rst
> +* The application can request the reader to be created with unique listening locators, using a
```suggestion
* The application can request the reader to be created with unique listening locators. This is done using a
```

2021-02-25 06:46 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=747)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/747/)

2021-02-25 06:59 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=748)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/748/)

2021-02-25 15:37 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=750)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/750/)

2021-02-26 09:02 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=752)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/752/)

2021-02-26 09:58 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=753)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/753/)

2021-02-26 12:03 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=754)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/754/)

2021-02-26 12:15 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=755)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/755/)

2021-02-26 12:25 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=756)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/756/)

2021-02-26 12:28 UTC, EduPonz submitted a review, later dismissed
LGTM with green CI 🚀

2021-02-26 12:37 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=757)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/757/)

2021-02-26 12:52 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=758)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/758/)

2021-03-01 07:50 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=759)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/759/)

2021-03-01 08:15 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=760)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/760/)

2021-03-01 08:30 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=761)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/761/)

2021-03-01 08:51 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=762)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/762/)

2021-03-01 09:29 UTC, EduPonz approved these changes
LGTM

2021-03-01 09:32 UTC, merged