FASTDDS_STATISTICS CMake option [10700]
eProsima/Fast-DDS-docs pull request #241
Opened 2021-03-04 11:15 UTC by JLBuenoLopez-eProsima

Documentation of the new CMake option FASTDDS_STATISTICS which enables the compilation of the Fast DDS Statistics module specific code.

Signed-off-by: JLBuenoLopez-eProsima joseluisbueno@eprosima.com

2021-03-04 13:56 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=770)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/770/)

2021-03-05 11:11 UTC, EduPonz requested changes

2021-03-05 11:11 UTC, EduPonz commented on docs/fastdds/statistics/includes/intro.rst
> +By default, Fast DDS does not compile this tool because it may entail affecting the application performance.
```suggestion
By default, Fast DDS does not compile this module because it may entail affecting the application performance.
```

2021-03-05 11:31 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=778)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/778/)

2021-03-05 11:33 UTC, EduPonz commented
Failure is caused by the target branch. I'll update it after this merge

2021-03-05 11:33 UTC, merged