Port documentation to CMake [10864]
eProsima/Fast-DDS-docs pull request #245
Opened 2021-03-12 06:58 UTC by EduPonz

This PR ports the documentation over to CMake:
* Makefile no longer exists, so its commands are not valid anymore
* Build is performed with either `cmake --build` or `colcon build`. This PR adds build options:
    * `BUILD_DOCUMENTATION` -> Whether to build the sphinx docs. Defaults ON
    * `COMPILE_TESTS` -> Whether to build the tests. Defaults ON
    * `FASTDDS_DOCS_BUILDER` -> Select a builder for sphinx. All the options that where available in the Makefile are still available. Defaults html
* Tests are moved to CTest so they can be run with `ctest` or `colon test`
* Documentation is installed
* README.md has been updated to reflect the new building methods

Merging this PR entails that:
* Current CI jobs will need to be updated.
* It offers the possibility to test the documentation with every Fast DDS PR, since now it can be built and test with `colcon`. Doing so will prevent merging Fast DDS PR with spelling errors in the doxygen comments, which right now breaks the documentation tests every now and then.
* External contributions are made easier, since with this PR, everyone can build and run the documentation tests locally, whereas before there was a dependency with eProsima's intranet.

2021-03-26 11:08 UTC, JLBuenoLopez-eProsima requested changes

2021-03-26 11:08 UTC, JLBuenoLopez-eProsima commented on code/grep.py
> +# Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
# Copyright 2021 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2021-03-26 11:08 UTC, JLBuenoLopez-eProsima commented on code/CMakeLists.txt
> +# Check that all cpp snippets are on the CPP files so they are compiled
```suggestion
# Check that all cpp snippets are on the CPP files and not in the RST files so they are compiled
```

2021-03-26 11:08 UTC, JLBuenoLopez-eProsima commented on code/CMakeLists.txt
> +# Check that all XML snippets are on the XML files so they are tested
```suggestion
# Check that all XML snippets are on the XML files and not in the RST files so they are tested
```

2021-03-31 14:57 UTC, EduPonz commented on README.md
> +    git clone https://github.com/eProsima/Fast-RTPS-docs fastdds-docs
I'm also inclined to that option. However, I'd wait until this PR is merged to do so, cause right now it does not make much sense. After this is merge, we can patch both repos

2021-04-06 12:36 UTC, EduPonz commented on README.md
> +    docs <abs_path_to_docs_repo>/fastdds-docs/build/html
I'm not able to reproduce this

2021-04-06 12:42 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=837)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/837/)

2021-04-06 14:06 UTC, JLBuenoLopez-eProsima commented on CMakeLists.txt
> +    endif()
Finally, only `html` builder is going to be supported.

2021-04-06 14:07 UTC, JLBuenoLopez-eProsima commented on CMakeLists.txt
> +        text man texinfo gettext changes xml pseudoxml pdf)
Only `html` builder is going to be supported.

2021-04-06 14:08 UTC, JLBuenoLopez-eProsima commented on Makefile
> -	@echo "Build finished. The PDF Files are in $(BUILDDIR)/pdf"
Only `html` builder is going to be supported.

2021-04-06 14:24 UTC, JLBuenoLopez-eProsima commented on README.md
> +| latexpdf   | Generate LaTeX files and run them through pdflatex         |
Only `html` builder is going to be supported.

2021-04-07 07:59 UTC, JLBuenoLopez-eProsima reviewed
Just a couple of small things.

2021-04-07 07:59 UTC, JLBuenoLopez-eProsima commented on README.md
> +The following guide has been developed and tested in Ubuntu 20.04.
I have not been able to build on Windows. On one hand, CMake is not able to find OpenSSL which is required. I have followed this [instructions](https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_windows.html#openssl) but they are not working for me...

After disabling OpenSSL in the CMakeLists files, the following error appears:

```
CUSTOMBUILD : Configuration error : 
   There is a programmable error in your configuration file:
   OSError: [WinError 126] The specified module could not be found
```

Consequently, I agree to keep the statement that this has only been developed and tested on Ubuntu.

2021-04-07 08:23 UTC, JLBuenoLopez-eProsima submitted a review, later dismissed
LGTM!

2021-04-07 08:23 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=840)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/840/)

2021-04-07 09:36 UTC, richiprosima commented
Buildstatus:[![BuildStatus](http://jenkins.eprosima.com:8080/buildStatus/icon?job=fastdds_docs_manual&build=3)](http://jenkins.eprosima.com:8080/job/fastdds_docs_manual/3/)

2021-04-07 09:37 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=841)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/841/)

2021-04-07 10:49 UTC, richiprosima commented
Buildstatus:[![BuildStatus](http://jenkins.eprosima.com:8080/buildStatus/icon?job=fastdds_docs_manual&build=5)](http://jenkins.eprosima.com:8080/job/fastdds_docs_manual/5/)

2021-04-07 10:50 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=842)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/842/)

2021-04-07 10:58 UTC, JLBuenoLopez-eProsima approved these changes
Good catch!

2021-04-07 11:09 UTC, richiprosima commented
Buildstatus:[![BuildStatus](http://jenkins.eprosima.com:8080/buildStatus/icon?job=fastdds_docs_manual&build=6)](http://jenkins.eprosima.com:8080/job/fastdds_docs_manual/6/)

2021-04-07 11:31 UTC, richiprosima commented
Buildstatus:[![BuildStatus](http://jenkins.eprosima.com:8080/buildStatus/icon?job=fastdds_docs_manual&build=7)](http://jenkins.eprosima.com:8080/job/fastdds_docs_manual/7/)

2021-04-07 12:40 UTC, merged