[10994] Add PropertyPolicyQos Options section
eProsima/Fast-DDS-docs pull request #251
Opened 2021-03-25 10:03 UTC by JLBuenoLopez-eProsima

Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>

2021-03-25 10:18 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=816)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/816/)

2021-03-25 11:03 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=818)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/818/)

2021-03-25 13:41 UTC, EduPonz requested changes

2021-03-25 13:41 UTC, EduPonz commented on docs/fastdds/property_policies/logging.rst
> +.. note::
I'd promote these to warnings

2021-03-25 13:41 UTC, EduPonz commented on docs/fastdds/property_policies/statistics.rst
> +Statistics Module Settings
I'd say this is a non-consolidated QoS that we hope to promote to extension one day

2021-03-25 15:04 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=823)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/823/)

2021-03-26 07:27 UTC, EduPonz approved these changes
LGTM

2021-03-26 07:28 UTC, merged