Update to new api to set static edp xml content
eProsima/Fast-DDS-docs pull request #254
Opened 2021-03-26 08:29 UTC by richiware

Depends on eProsima/Fast-DDS#1818

2021-03-26 08:39 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=824)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/824/)

2021-03-26 09:20 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=825)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/825/)

2021-03-26 12:54 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=826)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/826/)

2021-03-29 13:28 UTC, EduPonz requested changes

2021-03-29 13:28 UTC, EduPonz commented on docs/fastdds/discovery/static.rst
> +|    :start-after: //CONF_STATIC_DISCOVERY_XML_FILE    |
This is not correct

2021-03-29 13:28 UTC, EduPonz commented on docs/fastdds/discovery/static.rst
> +|    :start-after: //CONF_STATIC_DISCOVERY_XML_DATA    |
This is not correct

2021-03-29 13:28 UTC, EduPonz commented on docs/fastdds/discovery/static.rst
> +STATIC EDP XML Content Specification
As I said in eProsima/Fast-DDS#1818, I like configuration better
```suggestion
STATIC EDP XML Configuration Specification
```

2021-03-29 14:29 UTC, EduPonz requested changes

2021-03-29 14:29 UTC, EduPonz commented on code/DDSCodeTester.cpp
> +        //CONF_STATIC_DISCOVERY_XML_FILE
I think this one should be removed in favor of the other one

2021-03-29 14:47 UTC, EduPonz approved these changes

2021-03-29 14:47 UTC, EduPonz commented
Please correct DCO

2021-03-29 17:00 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=829)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/829/)

2021-03-30 05:58 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=830)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/830/)

2021-03-30 06:19 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=FastRTPS%20Docs%20Manual&build=831)](http://jenkins.eprosima.com:8080/job/FastRTPS%20Docs%20Manual/831/)

2021-03-30 06:49 UTC, EduPonz approved these changes

2021-03-30 06:50 UTC, merged