Add cs to FastDDS Gen [12318]
eProsima/Fast-DDS-docs pull request #278
Opened 2021-08-02 13:02 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2021-08-31 07:14 UTC, MiguelCompany requested changes

2021-08-31 07:14 UTC, MiguelCompany commented on docs/fastddsgen/dataTypes/dataTypes.rst
> +To activate case sensitive use option :code:`-cs` when execute *Fast DDS-Gen* (see :ref:`fastddsgen_supported_options`).
```suggestion
To activate case sensitivity use option :code:`-cs` when running *Fast DDS-Gen* (see :ref:`fastddsgen_supported_options`).
```

2021-08-31 07:14 UTC, MiguelCompany commented on docs/fastddsgen/usage/usage.rst
> +| -cs                 | Activates Case Sensitive                                                                       |
```suggestion
| -cs                 | Enables Case Sensitivity                                                                       |
```

2021-09-01 05:47 UTC, jparisu commented on docs/fastddsgen/dataTypes/dataTypes.rst
> +To activate case sensitive use option :code:`-cs` when execute *Fast DDS-Gen* (see :ref:`fastddsgen_supported_options`).
:+1:

2021-09-01 05:48 UTC, jparisu commented on docs/fastddsgen/usage/usage.rst
> +| -cs                 | Activates Case Sensitive                                                                       |
:+1:

2021-09-01 06:46 UTC, MiguelCompany requested changes

2021-09-01 06:46 UTC, MiguelCompany commented on docs/fastddsgen/dataTypes/dataTypes.rst
> +To activate case sensitiveity use option :code:`-cs` when running *Fast DDS-Gen* (see
```suggestion
To activate case sensitivity use option :code:`-cs` when running *Fast DDS-Gen* (see
```

2021-09-01 06:46 UTC, MiguelCompany commented on docs/fastddsgen/usage/usage.rst
> +| -cs                 | Enables Case Sensitiveity                                                                      |
```suggestion
| -cs                 | Enables Case Sensitivity                                                                       |
```

2021-09-01 07:05 UTC, MiguelCompany approved these changes

2021-09-01 07:05 UTC, merged