Include mention to new HelloWorldExampleDiscoveryServer [12368]
eProsima/Fast-DDS-docs pull request #288
Opened 2021-10-04 13:08 UTC by juanlofer-eprosima

Signed-off-by: Juan López Fernández <juanlopez@eprosima.com>

2023-03-16 14:52 UTC, JLBuenoLopez-eProsima commented
@juanlofer-eprosima What is the status of this Draft? Can it be closed? Do we have to update the related Fast DDS PR? If it is attached to a Fast DDS PR, please assign the same milestone. Thanks!

2023-06-14 07:59 UTC, juanlofer-eprosima commented
@richiprosima please test this

2023-06-15 06:54 UTC, JesusPoderoso requested changes

2023-06-15 06:54 UTC, JesusPoderoso commented on docs/fastdds/discovery/discovery_server.rst
> +`here <https://github.com/eProsima/Fast-DDS/tree/master/examples/cpp/dds/DiscoveryServerExample>`_.
```suggestion
You may also have a look at the *eProsima Fast DDS* Github repository, which contains 
`an example <https://github.com/eProsima/Fast-DDS/tree/master/examples/cpp/dds/DiscoveryServerExample>`_ 
similar to the one discussed in this section, as well as multiple other examples for different use cases. 
```

2023-06-15 08:47 UTC, merged