[12987] Add dynamic network interfaces documentation
eProsima/Fast-DDS-docs pull request #301
Opened 2021-12-03 12:41 UTC by JLBuenoLopez-eProsima

Related to eProsima/Fast-DDS#2310

Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>

2021-12-09 14:57 UTC, JLBuenoLopez-eProsima commented
[CI run PASSES](http://jenkins.eprosima.com:8080/job/fastdds_docs_manual/168/) (but fails to assign result to this PR)

2021-12-15 15:44 UTC, EduPonz commented on docs/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.rst
> +The unicast metatraffic list is automatically initialized taking into account the network interfaces that are available
An uneducated reader might not know what a `unicast metatraffic list` is 🤓

2021-12-15 15:45 UTC, EduPonz commented on docs/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.rst
> +in order to initialize a unicast locator in said network, so communication can be established over that new network
Too many networks
```suggestion
in order to initialize a unicast locator in said network, so communication can be established over that new
```

2021-12-15 15:48 UTC, EduPonz commented on docs/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.rst
> +This attribute is set within the `builtin` member of |DomainParticipantQos::wire_protocol-api| contained in the
```suggestion
These attributes are set within the `builtin` member of |DomainParticipantQos::wire_protocol-api| contained in the
```

2021-12-15 15:48 UTC, EduPonz commented on docs/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.rst
> +enabled.
I like the intention, but I'm not convinced with the formulation

2021-12-15 15:49 UTC, EduPonz commented on docs/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.rst
> +it can simply be the current DomainParticipant QoS (obtained with |DomainParticipant::get_qos-api|).
Maybe a snippet? Something that creates the participant, detects new interfaces, and then notifies Fast DDS

2021-12-16 10:01 UTC, JLBuenoLopez-eProsima commented on docs/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.rst
> +to receive incoming meta data traffic.
It seems that the most common way is `metatraffic`

2021-12-16 13:59 UTC, EduPonz requested changes

2021-12-16 13:59 UTC, EduPonz commented on docs/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.rst
> +Participant announcement messages (:ref:`disc_phases`).
```suggestion
Participant announcement messages (see :ref:`disc_phases`).
```

2021-12-16 13:59 UTC, EduPonz commented on docs/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.rst
> +Such Participant announcement includes information about the unicast addresses and ports (locators) where the
```suggestion
Such Participant announcement includes information about the unicast address-port pairs (a.k.a locators) where the
```

2021-12-16 13:59 UTC, EduPonz commented on docs/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.rst
> +In case that the user wants to include new network interfaces at run-time some prerequisites have to be fulfilled.
```suggestion
In case that the user wants to include new network interfaces at run-time, some prerequisites have to be fulfilled.
```

2021-12-16 15:14 UTC, EduPonz approved these changes
LGTM

2021-12-20 07:55 UTC, EduPonz commented
@richiprosima please test docs

2021-12-20 09:14 UTC, merged