[13804] Topic, instances and keys
eProsima/Fast-DDS-docs pull request #324
Opened 2022-02-07 15:56 UTC by JLBuenoLopez-eProsima

Include a section in the documentation explaining in detail the instances.

2022-02-08 10:41 UTC, EduPonz requested changes

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +Even though, by definition, a Topic corresponds to a single data type, it is possible that several topics may refer to
```suggestion
Even though, by definition, a Topic corresponds to a single data type, it is possible that several topic instances may refer to
```

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +The different instances gathered under the same topic are distinguishable by means of some data fields that form the key
```suggestion
The different instances gathered under the same topic are distinguishable by means of one or more data fields that form the key
```

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +The rule is simple: different data values with the same key value represent successive values for the same instance,
```suggestion
The rule is simple: different data values with the same key value represent successive data samples for the same instance,
```

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +while different data values with different keys represent different instances.
```suggestion
while different data values with different keys represent different topic instances.
```

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +Consequently, there is less memory usage and no new discovery (with the related metatraffic involved as explained in
```suggestion
Consequently, there is less memory usage, and no new discovery (with the related metatraffic involved as explained in
```

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +For example, the :ref:`historyqospolicy` is kept for each instance in the DataWriter.
```suggestion
Another advantage is that several QoS are applied per Topic instance; e.g. the :ref:`historyqospolicy` is kept for each instance in the DataWriter.
```

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +
I'dd add a title `Instance advantages`

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +
Move examples to separate sections after lifecycle

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +The key identifying the instances could be the airline name and the flight number and the sample the location of each
```suggestion
The key identifying the instances could be the airline name and the flight number, while the sample data would be the location of each
```

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +flight being tracked.
```suggestion
flight being tracked at any given time.
```

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +Instead of creating a DataWriter, DataReader and Topic each time a flight takes off, the same DDS entities may be reused
I'd elaborate that the plane would have the DataWriter and the control tower a single DataReader managing several instances (one per flight)

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +The instance key is analogous to the primary key in a database (unique identifier of something within your data).
```suggestion
The instance key is analogous to the primary key in the database (unique identifier of something within the data).
```

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +Writing a new sample to the instance is similar to insert/update the database; and disposing the instance is like
```suggestion
In this scenario, writing a new sample to the instance is similar to insert/update the database; and disposing the instance is like
```

2022-02-08 10:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +removing the data corresponding to the given primary key from the database.
```suggestion
deleting the data corresponding to the given primary key from the database.
```

2022-02-08 13:41 UTC, EduPonz requested changes

2022-02-08 13:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +.. literalinclude:: /../code/DDSCodeTester.cpp
Please de-indent

2022-02-08 13:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +        string<256> airline_name;
```suggestion
        @key string<256> airline_name;
```

2022-02-08 13:41 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +        int flight_number;
I'd put this as part of the key as well

2022-02-08 14:12 UTC, EduPonz requested changes

2022-02-08 14:12 UTC, EduPonz commented on docs/fastdds/dds_layer/topic/instances.rst
> +   :dedent: 8
Please look at the generated HTML
```suggestion
   :dedent: 12
```

2022-02-08 14:37 UTC, MiguelCompany approved these changes

2022-02-08 14:44 UTC, merged

2022-02-09 06:25 UTC, richiware commented on docs/fastdds/dds_layer/topic/instances.rst
> +Even though, by definition, a Topic corresponds to a single data type, it is possible that several topic instances may
Suggestion:

A Topic is linked to a data type and each data sample related to a Topic could be seen as an update in the information described by the data type. But it is possible to add a logical separation and have several instances of a Topic, and a data sample should be an update of the information about a concrete  instance.