[13805] Use Case - Record Replay with Rosbag
eProsima/Fast-DDS-docs pull request #326
Opened 2022-02-08 12:09 UTC by jsantiago-eProsima

Signed-off-by: Javier Santiago <javiersantiago@eprosima.com>

2022-02-08 14:27 UTC, EduPonz requested changes

2022-02-08 14:27 UTC, EduPonz commented on docs/fastdds/use_cases/rosbag_capture/rosbag_capture.rst
> +Rosbag2 is a ROS application that can be used to capture DDS messages and store them on an sqlite database. This allows
In general, please break line after each sentence period

2022-02-08 14:27 UTC, EduPonz commented on docs/fastdds/use_cases/rosbag_capture/rosbag_capture.rst
> +Rosbag2 interactions with a non-ROS2 Fast DDS application
```suggestion
Rosbag2 interactions with a native Fast DDS application
```

2022-02-08 14:27 UTC, EduPonz commented on docs/fastdds/use_cases/rosbag_capture/rosbag_capture.rst
> +Rosbag2 is a ROS application that can be used to capture DDS messages and store them on an sqlite database. This allows
```suggestion
Rosbag2 is a ROS 2 application that can be used to capture DDS messages and store them on an sqlite database. This allows 
```

2022-02-08 14:27 UTC, EduPonz commented on docs/fastdds/use_cases/rosbag_capture/rosbag_capture.rst
> +Being a ROS2 application, to install rosbag requires to have the ROS2 repository for the ROS2 distribution of choice
In general
```suggestion
Being a ROS 2 application, to install rosbag requires to have the ROS 2 repository for the ROS 2 distribution of choice
```

2022-02-08 14:27 UTC, EduPonz commented on docs/fastdds/use_cases/rosbag_capture/rosbag_capture.rst
> +     module idl {
I'd clearly state that the IDL module must be named `idl`
```suggestion
     module idl {
```

2022-02-08 14:27 UTC, EduPonz commented on docs/fastdds/use_cases/rosbag_capture/rosbag_capture.rst
> +.. code-block:: bash
Please format IDL
```suggestion
.. code-block:: idl
```

2022-02-08 15:46 UTC, JLBuenoLopez-eProsima approved these changes
Section under work (notice being shown at the beginning of the section). I approve conditional to keep working into improving this section.

2022-02-08 15:51 UTC, merged

2022-02-10 14:48 UTC, jsantiago-eProsima commented on docs/fastdds/use_cases/rosbag_capture/rosbag_capture.rst
> +   source new_typesupport/install/setup.bash
Not necessarily true. The user might want to replay the messages from a different terminal or at a later date.