[13829 ] add non-root users to the softhsm2 group
eProsima/Fast-DDS-docs pull request #332
Opened 2022-02-10 08:43 UTC by MiguelBarro

Include an explanation of the softhsm2 group on linux

2022-02-10 08:52 UTC, jsantiago-eProsima requested changes

2022-02-10 08:52 UTC, jsantiago-eProsima commented on docs/installation/sources/sources_linux.rst
> +Note that the *softhsm2* package creates a new group called *softhsm2*. In order
```suggestion
Note that the *softhsm* package creates a new group called *softhsm*. In order
```

2022-02-10 10:21 UTC, jsantiago-eProsima submitted a review, later dismissed
LGTM

2022-02-18 06:41 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2022-02-22 09:59 UTC, jsantiago-eProsima commented
@richiprosima please test this

2022-02-24 09:46 UTC, merged