Update large_data.rst
eProsima/Fast-DDS-docs pull request #341
Opened 2022-02-15 13:21 UTC by xander-m2k

Added information about txqueuelen modification.

2022-03-11 09:31 UTC, MiguelCompany requested changes
Sorry for the delay in reviewing this.

The content looks good to me, but there are several changes related to style that need to be addressed.

2022-03-11 09:31 UTC, MiguelCompany commented on docs/fastdds/use_cases/large_data/large_data.rst
> +Increasing the Transmit Queue Length of an interface
The link tag above `.. _flow-controllers:` should be moved below the newly inserted section.

2022-03-11 09:31 UTC, MiguelCompany commented on docs/fastdds/use_cases/large_data/large_data.rst
> +The Transmit Queue Length (``txqueuelen``) is a TCP/UDP/IP stack network interface value that sets the number of packets allowed per kernel transmit queue of a network interface device. By default, t
Please insert line breaks after each sentence. This is part of our style guidelines for documentation.

Also ensure that lines have less than 120 characters.

2022-03-11 09:31 UTC, MiguelCompany commented on docs/fastdds/use_cases/large_data/large_data.rst
> +The Transmit Queue Length (``txqueuelen``) is a TCP/UDP/IP stack network interface value that sets the number of packets allowed per kernel transmit queue of a network interface device. By default, t
Add `txqueuelen` [here](https://github.com/eProsima/Fast-DDS-docs/blob/master/docs/spelling_wordlist.txt) so it is considered a valid work by the spell checker.

2022-03-11 09:46 UTC, JLBuenoLopez-eProsima reviewed
As a suggestion (but not blocking the merging of this PR), just before this new section the is [another](https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/large_data/large_data.html#finding-out-system-maximum-values) which is also platform-dependent. In this case the configuration of both Windows and Linux is explained. I think the Windows configuration should be included at some point. Maybe the same structure can be followed: a subsection for Windows and another for Linux, leaving a note in the Windows section that it is under development.

2022-03-11 09:58 UTC, MiguelCompany commented
> As a suggestion (but not blocking the merging of this PR), just before this new section the is [another](https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/large_data/large_data.html#finding-out-system-maximum-values) which is also platform-dependent. In this case the configuration of both Windows and Linux is explained. I think the Windows configuration should be included at some point. Maybe the same structure can be followed: a subsection for Windows and another for Linux, leaving a note in the Windows section that it is under development.

Or even better, we could use tabs, as it is done [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/property_policies/non_consolidated_qos.html#physical-data-in-discovery-information)

2022-03-11 10:19 UTC, MiguelCompany commented
@xander-m2k Would you mind doing a `git rebase -i` so your commits are the only ones on this PR ?

2022-03-11 10:24 UTC, EduPonz requested changes
Thanks I lot @xander-m2k , we really appreciate your effort here. One nit-pick is that we also use reported speech see [Contributing](https://github.com/eProsima/Fast-DDS-docs#contributing)

2022-03-11 10:27 UTC, xander-m2k commented
> @xander-m2k Would you mind doing a `git rebase -i` so your commits are the only ones on this PR ?

I rebased, but I notice I signed-off all of the commits, how do I undo that?

2022-03-11 10:48 UTC, MiguelCompany commented
> > @xander-m2k Would you mind doing a `git rebase -i` so your commits are the only ones on this PR ?
> 
> I rebased, but I noticed I signed-off all of the commits, how do I undo that?

First do `git fetch eProsima`
Then `git rebase -i eProsima/master`
An editor will open with several `pick` commands. Leave only the pick commands for your commits.
Then save and close the editor.
Then do `git push -f`

2022-03-11 11:22 UTC, xander-m2k commented
> > > @xander-m2k Would you mind doing a `git rebase -i` so your commits are the only ones on this PR ?
> > 
> > 
> > I rebased, but I noticed I signed-off all of the commits, how do I undo that?
> 
> First do `git fetch eProsima` Then `git rebase -i eProsima/master` An editor will open with several `pick` commands. Leave only the pick commands for your commits. Then save and close the editor. Then do `git push -f`

Finally got it working with:
`git fetch https://github.com/eProsima/Fast-DDS-docs.git`
`git rebase -i FETCH_HEAD`
`git push -f`

2022-03-11 11:39 UTC, MiguelCompany commented
@xander-m2k Great!

@JLBuenoLopez-eProsima Would you mind reviewing this?

2022-03-11 11:43 UTC, JLBuenoLopez-eProsima approved these changes
Thanks @xander-m2k!

We will proceed and merge your contribution if the CI passes. Then I will prepare a follow-up PR fixing the style (use the reported style, more impersonal and technical), adding the Windows subsection/tab, etc.

2022-03-14 08:56 UTC, JLBuenoLopez-eProsima commented
Hi @xander-m2k,

I have added a couple of commits fixing our CI tests and doing some modifications to conform with our documentation style. I have also generalized using both the `ifconfig` and the `ip` command. I have removed the modification of the `rc.local` file because there is no standard way to run scripts at boot time (`rc.local` has been removed in the latest Ubuntu releases) so I think we should explain how to set the value but leave to the user the way to ensure that the value is kept after rebooting.

If you have any comment, please let me know!

2022-03-14 09:01 UTC, MiguelCompany requested changes

2022-03-14 09:05 UTC, MiguelCompany approved these changes
LGTM with green CI

2022-03-14 09:54 UTC, merged