[14528] @value annotation is unimplemented
eProsima/Fast-DDS-docs pull request #368
Opened 2022-05-10 06:05 UTC by JLBuenoLopez-eProsima

Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>

2022-05-20 10:50 UTC, EduPonz requested changes
I think this ought to be changed in Fast DDS-Gen help as well

2022-05-20 10:50 UTC, EduPonz commented on docs/fastddsgen/dataTypes/dataTypes.rst
> +| @value                  | Unimplemented.                                                          |
I wouldn't remove the description
```suggestion
| @value                  | [Unimplemented] Allows to set a constant value to any element.   |
```

2022-05-23 07:53 UTC, JLBuenoLopez-eProsima commented
Which help are you referring to? Fast DDS-Gen help only refers to the tool options and not to the annotation support or other implementation details. I do not think we should change this.

2022-06-08 08:53 UTC, EduPonz approved these changes
LGTM

2022-06-08 08:54 UTC, merged