[15628] XML configuration for Ownership QoS
eProsima/Fast-DDS-docs pull request #403
Opened 2022-09-22 14:23 UTC by MRicoIE2C

XML examples added to show the possibility of configuring ownership QoS policy from XML.
Related to Fast DDS PR: https://github.com/eProsima/Fast-DDS/pull/2967.

2022-09-23 07:13 UTC, jsantiago-eProsima requested changes
This comment is actually only tangentially related to this PR. Now that we are modifying things related to ownership, we should clarify Ownership's behavior when two writers have the same strength. This is something that slipped past my Ownership review.

2022-09-23 07:35 UTC, MRicoIE2C commented
> This comment is actually only tangentially related to this PR. Now that we are modifying things related to ownership, we should clarify Ownership's behavior when two writers have the same strength. This is something that slipped past my Ownership review.

Done: 42e068e9 Refs #15628: Explain case of same strengths

2022-09-23 07:50 UTC, jsantiago-eProsima commented on docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> +  the DataWriter with minimum `GUID` value would be the owner of the topic.
```suggestion
  the DataWriter with a lower `GUID` value would be the owner of the topic.
```
Small nitpick

2022-09-23 08:01 UTC, MRicoIE2C commented on docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> +  the DataWriter with minimum `GUID` value would be the owner of the topic.
Done:
2ca357ce Refs #15628: Nitpick

2022-09-23 08:28 UTC, jsantiago-eProsima approved these changes

2022-09-26 09:02 UTC, jsantiago-eProsima submitted a review, later dismissed

2022-09-27 06:23 UTC, MRicoIE2C commented
I have seen that it lacks explanation on this chapter: https://fast-dds.docs.eprosima.com/en/latest/fastdds/xml_configuration/common.html#qos regarding ownership. 
I am going to add it now.

2022-09-28 17:54 UTC, EduPonz approved these changes

2022-09-28 18:27 UTC, merged