[16171] <2.3.x> Fast DDS 2.3.6 release notes and bump version to v2.3.6
eProsima/Fast-DDS-docs pull request #423
Opened 2022-11-22 14:34 UTC by JLBuenoLopez-eProsima

2022-11-22 15:20 UTC, JLBuenoLopez-eProsima commented
CI is failing for the same reason as in this other [PR](https://github.com/eProsima/Fast-DDS-docs/pull/390#issuecomment-1195063425)

2022-11-24 09:15 UTC, EduPonz requested changes

2022-11-24 09:15 UTC, EduPonz commented on docs/notes/notes.rst
> +5. Fix data races when creating DataWriters.
Please remove item `23` just after this.

2022-11-24 09:25 UTC, EduPonz approved these changes

2022-11-24 09:25 UTC, merged