Add request-reply use case
eProsima/Fast-DDS-docs pull request #436
Opened 2022-12-22 11:48 UTC by richiware

This PR adds a new use case: Request-Replyg communication

2023-01-30 10:05 UTC, JLBuenoLopez-eProsima requested changes
A few nitpicks

2023-01-30 10:05 UTC, JLBuenoLopez-eProsima commented on docs/fastdds/use_cases/request_reply/request_reply.rst
> +the stored identifier in |WriteParams-related_sample_identity-api|.
```suggestion
After processing the request, the server should send the reply to the client with the related request attached.
This is done assigning the stored identifier in |WriteParams-related_sample_identity-api|.
```

2023-01-30 10:05 UTC, JLBuenoLopez-eProsima commented on docs/fastdds/use_cases/request_reply/request_reply.rst
> +the client application should identify which reply is an answer for its request.
```suggestion
the client application should identify if the reply received is the one expected for its request.
```

2023-01-30 10:05 UTC, JLBuenoLopez-eProsima commented on docs/fastdds/use_cases/request_reply/request_reply.rst
> +For this the client application have to compare the stored |SampleIdentity-api| with the incomming
```suggestion
For this the client application has to compare the stored |SampleIdentity-api| with the incoming
```

2023-01-31 10:44 UTC, richiware commented on docs/fastdds/use_cases/request_reply/request_reply.rst
> +2. In the client application creates a DataWriter for the request and a DataReader for the reply.
Done in ba11b18e

2023-01-31 10:45 UTC, richiware commented on docs/fastdds/use_cases/request_reply/request_reply.rst
> +3. In the server application creates a DataWriter for the reply and a DataReader for the request.
Done in ba11b18e

2023-01-31 10:45 UTC, richiware commented on docs/fastdds/use_cases/request_reply/request_reply.rst
> +the client application should identify which reply is an answer for its request.
Done in ba11b18e

2023-01-31 10:47 UTC, richiware commented on code/DDSCodeTester.cpp
> +    Topic* reply_topic = participant->create_topic("CalculatorReply", reply_type.get_type_name(), TOPIC_QOS_DEFAULT);
I think there is a significant difference that has to be shown: in one application the request topic is for the datareader and in the other one for the datawriter, and the same in reply topic.

2023-01-31 11:19 UTC, JLBuenoLopez-eProsima approved these changes
LGTM!

2023-02-01 06:47 UTC, merged