[16732] on_unacknowledged_sample_removed documentation
eProsima/Fast-DDS-docs pull request #439
Opened 2023-01-10 11:41 UTC by JLBuenoLopez-eProsima

This PR includes documentation of the new DataWriterListener callback `on_unacknowledged_sample_removed`. It should be merged once the implementation has been done in Fast DDS.

Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>

2023-01-13 10:00 UTC, MiguelCompany requested changes

2023-01-13 12:24 UTC, MiguelCompany approved these changes

2023-02-07 15:04 UTC, MiguelCompany requested changes

2023-02-07 15:04 UTC, MiguelCompany commented on code/DDSCodeTester.cpp
> +            const InstanceHandle_t& instance)
I would like the CI to fail if we break the API in the future...

```suggestion
    void on_unacknowledged_sample_removed(
            DataWriter* writer,
            const InstanceHandle_t& instance) override
```

2023-02-07 15:35 UTC, MiguelCompany approved these changes
LGTM with green CI

2023-02-08 06:51 UTC, MiguelCompany commented
New manual CI [here](http://jenkins.eprosima.com:8080/job/fastdds_docs_manual/636)

2023-02-08 09:36 UTC, JLBuenoLopez-eProsima commented
[Another manual CI](http://ci.intranet.eprosima.com:8080/job/fastdds_docs_manual/640/)

2023-02-08 10:20 UTC, merged