[18066] Monitor Service Documentation
eProsima/Fast-DDS-docs pull request #483
Opened 2023-04-17 05:53 UTC by Mario-DL

This PR adds the proper documentation for `Fast DDS` [feature/monitor-service/high-level-empty-api](https://github.com/eProsima/Fast-DDS/tree/feature/monitor-service/high-level-empty-api)

2023-04-17 06:04 UTC, Mario-DL commented
Running Manual CI here:
[![Build Status](http://ci.intranet.eprosima.com:8080/job/fastdds_docs_manual/708/badge/icon)](http://ci.intranet.eprosima.com:8080/job/fastdds_docs_manual/708/)

2023-04-17 08:36 UTC, Mario-DL commented
Manual CI running here
[![Build Status](http://jenkins.eprosima.com:8080/job/fastdds_docs_manual/710/badge/icon)](http://jenkins.eprosima.com:8080/job/fastdds_docs_manual/710/)

2023-04-17 09:41 UTC, Mario-DL commented
Manual CI running here
[![Build Status](http://jenkins.eprosima.com:8080/view/Fast%20DDS/job/fastdds_docs_manual/712/badge/icon)](http://ci.intranet.eprosima.com:8080/view/Fast%20DDS/job/fastdds_docs_manual/712/)

2023-04-21 09:17 UTC, Mario-DL commented
Manual run here [![Build Status](http://jenkins.eprosima.com:8080/job/fastdds_docs_manual/720/badge/icon)](http://ci.intranet.eprosima.com:8080/job/fastdds_docs_manual/720/)

2023-04-25 10:21 UTC, jsantiago-eProsima requested changes

2023-04-25 10:21 UTC, jsantiago-eProsima commented on docs/fastdds/monitor_service/monitor_service_topics.rst
> +    GUID_t entity_guid @Key
Same question as above regarding the annotations.

2023-04-25 10:21 UTC, jsantiago-eProsima commented on docs/fastdds/monitor_service/monitor_service_topics.rst
> +The ``MonitorServiceResponseData`` data structure consists on the following fields:
```suggestion
The ``MonitorServiceResponseData`` data structure consists of the following fields:
```

2023-04-25 10:21 UTC, jsantiago-eProsima commented on docs/fastdds/monitor_service/monitor_service_topics.rst
> +  with last MonitorServiceEventData published in the Monitor Service Event's Topic.
```suggestion
  with the last MonitorServiceEventData published in the Monitor Service Event's Topic.
```

2023-04-25 10:21 UTC, jsantiago-eProsima commented on docs/fastdds/monitor_service/monitor_service_topics.rst
> +      LocatorList used_locators
We should turn this into a cpp code block

2023-04-25 10:21 UTC, jsantiago-eProsima commented on docs/fastdds/monitor_service/monitor_service_topics.rst
> +    vector<SampleLostStatus> sample_lost_status
Same here, we are using C++ nomenclature here.

2023-06-05 12:21 UTC, Mario-DL commented on docs/fastdds/monitor_service/monitor_service_configuration.rst
> +through the |DomainParticipant::enable-monitor-service-api| and |DomainParticipant::disable-monitor-service-api| calls.
(I discussed it internally but for the moment the described API in the `Fast-DDS-Docs` is the DDS layer only)

2023-06-05 12:22 UTC, Mario-DL commented
I took into account the previous comments. But as I am refactoring the entire feature, I wont apply all of them

2023-06-07 07:25 UTC, Mario-DL commented
Manual run here
[![Build Status](http://jenkins.eprosima.com:8080/job/fastdds_docs_manual/badge/icon)](http://ci.intranet.eprosima.com:8080/job/fastdds_docs_manual/)

2023-06-07 08:36 UTC, Mario-DL commented
Manual run here [![Build Status](http://jenkins.eprosima.com:8080/job/fastdds_docs_manual/badge/icon)](http://ci.intranet.eprosima.com:8080/job/fastdds_docs_manual/)

2023-06-13 10:07 UTC, jsantiago-eProsima requested changes

2023-06-13 10:52 UTC, Mario-DL commented on docs/fastdds/monitor_service/intro.rst
> +The ``Monitor Service`` targets any application implementing the subscription side,
The subscriber side of the monitor service status topic. I will clarify it

2023-06-13 10:59 UTC, Mario-DL commented on docs/fastdds/monitor_service/monitor_service.rst
> +The *Fast DDS* Monitor Service is an extension of Fast DDS that
Nice distinction. It is a feature not an extension

2023-06-13 11:13 UTC, Mario-DL commented on docs/fastdds/monitor_service/monitor_service_topics.rst
> +The possible values are described in the following table:
Nice catch ! I thought I added it somewhere but I did not

2023-06-13 11:18 UTC, Mario-DL commented on docs/fastdds/monitor_service/monitor_service_topics.rst
> +The possible values are described in the following table:
It was remarked in the `note` within the `intro.rst` but I will introduce here a link to that as a reminder

2023-06-13 11:28 UTC, Mario-DL commented
Leaving a question here:
Is it correct to merge this PR regardless of the `feature/monitor-service/main` branch in `Fast DDS` or should we wait ? I mean, the documentation will fail to build until we merge that branch in `Fast DDS` (bascially due to the `API` references).

2023-06-13 11:32 UTC, Mario-DL commented
Manual CI here [![Build Status](http://jenkins.eprosima.com:8080/job/fastdds_docs_manual/771/badge/icon)](http://ci.intranet.eprosima.com:8080/job/fastdds_docs_manual/771/)

2023-06-13 12:08 UTC, MiguelCompany commented
> Leaving a question here: Is it correct to merge this PR regardless of the `feature/monitor-service/main` branch in `Fast DDS` or should we wait ? I mean, the documentation will fail to build until we merge that branch in `Fast DDS` (bascially due to the `API` references).

We will not merge till the feature is implemented and merged into Fast DDS master branch. In the mean time, just rename the branch of this PR to `feature/monitor-service/main`, and the PR builds will automagically use that Fast DDS branch

2023-06-13 12:49 UTC, closed without merging