[18066] Feature/monitor service/main
eProsima/Fast-DDS-docs pull request #506
Opened 2023-06-13 12:50 UTC by Mario-DL

This PR adds the proper documentation for Fast DDS [feature/monitor-service/high-level-empty-api](https://github.com/eProsima/Fast-DDS/tree/feature/monitor-service/high-level-empty-api)

This PR should be merged after the v2.11.x brach out is done!

2023-06-13 12:52 UTC, jsantiago-eProsima requested changes

2023-06-13 12:52 UTC, jsantiago-eProsima commented on docs/fastdds/monitor_service/monitor_service.rst
> +The *Fast DDS* Monitor Service is an feature of Fast DDS that
```suggestion
The *Fast DDS* Monitor Service is a feature of Fast DDS that
```

2023-06-13 13:16 UTC, jsantiago-eProsima requested changes

2023-06-13 13:32 UTC, Mario-DL commented on code/DDSCodeTester.cpp
> +        participant_with_mon_srv->enable_monitor_service();
Nice catch !

2023-06-14 06:58 UTC, jsantiago-eProsima approved these changes

2023-06-30 10:23 UTC, JLBuenoLopez-eProsima approved these changes
Reviewed commit 340ab5d.

2023-06-30 10:25 UTC, JLBuenoLopez-eProsima commented
Please, fix the CI failures: there is a line over the allowed character limit.

2023-07-03 07:43 UTC, JLBuenoLopez-eProsima submitted a review, later dismissed
LGTM

2023-12-12 06:59 UTC, JesusPoderoso commented on docs/fastdds/statistics/monitor_service/intro.rst
> +  including: the Proxy Data, incompatible qos, connections, liveliness, deadlines missed, inconsistent
```suggestion
  including: the Proxy data, incompatible QoS, connections, liveliness, deadlines missed, inconsistent
```

2023-12-12 06:59 UTC, JesusPoderoso commented on docs/fastdds/statistics/monitor_service/monitor_service_configuration.rst
> ++----------------------------------------------------------+
Tabs?

```suggestion
.. tabs::

  .. group-tab:: C++ API

    .. code-block:: cpp

      .. literalinclude:: /../code/DDSCodeTester.cpp
        :language: c++
        :dedent: 8
        :start-after: // FASTDDS_MONITOR_SERVICE_API
        :end-before: //!

    .. group-tab:: C++ Property

      .. literalinclude:: /../code/DDSCodeTester.cpp
        :language: c++
        :dedent: 8
        :start-after: // FASTDDS_MONITOR_SERVICE_PROPERTY
        :end-before: //!

    .. group-tab:: XML

      .. literalinclude:: /../code/XMLTester.xml
        :language: xml
        :start-after: <!-->DDS_MONITOR_SERVICE<-->
        :end-before: <!--><-->

    .. group-tab:: Environment Variable Linux

      .. code-block:: bash

        export FASTDDS_STATISTICS="MONITOR_SERVICE_TOPIC"

    .. group-tab:: Environment Variable Windows

      .. code-block:: bash

        set FASTDDS_STATISTICS=MONITOR_SERVICE_TOPIC
```

2023-12-12 07:51 UTC, Mario-DL commented on docs/fastdds/statistics/monitor_service/intro.rst
> +  including: the Proxy Data, incompatible qos, connections, liveliness, deadlines missed, inconsistent
(Applied the QoS thing)

2023-12-12 09:01 UTC, JesusPoderoso commented on code/DDSCodeTester.cpp
> +
Include the other way to enable monitor service through the statistics

```suggestion
        // Activate Fast DDS Monitor Service through properties
        pqos.properties().properties().emplace_back("fastdds.enable_monitor_service",
                "true");
                
        // Activate Fast DDS Monitor Service through statistics properties (other way)
        pqos.properties().properties().emplace_back("fastdds.statistics",
                "MONITOR_SERVICE_TOPIC");

```

2023-12-12 09:03 UTC, JesusPoderoso commented on docs/fastdds/statistics/monitor_service/monitor_service_configuration.rst
> +
Fix XML to display commented header section and append closing tag `</profiles>` at the end.

```suggestion
      .. literalinclude:: /../code/XMLTester.xml
        :language: xml
        :start-after: <!-->DDS_MONITOR_SERVICE<-->
        :end-before: <!--><-->
        :lines: 2-3,5-22
        :append: </profiles>

```

2023-12-12 10:00 UTC, JesusPoderoso requested changes

2023-12-12 10:15 UTC, JesusPoderoso approved these changes
LGTM

2023-12-12 10:46 UTC, merged