[18913] Expose PayloadPool in DDSDataWriter and DDSDataReader
eProsima/Fast-DDS-docs pull request #513
Opened 2023-06-20 15:23 UTC by JesusPoderoso

2023-06-25 11:50 UTC, EduPonz requested changes
Maybe it's a good idea to reopen this PR from a branch named the same as the PR in Fast DDS so that both CI run correctly

2023-06-25 11:50 UTC, EduPonz commented on docs/fastdds/dds_layer/publisher/dataWriter/createDataWriter.rst
> +That would allow customizing the management of the information exchanged between DataWriters and DataReaders.
```suggestion
This allows for customizing the management of the information exchanged between DataWriters and DataReaders.
```

2023-06-25 11:50 UTC, EduPonz commented on code/DDSCodeTester.cpp
> +        std::shared_ptr<CustomPayloadPool> payload_pool = std::make_shared<CustomPayloadPool>();
I don't this this would compile since `CustomPayloadPool` is not defined as far as I can tell.

2023-06-26 09:20 UTC, JesusPoderoso commented
Closing this PR, this changes have been moved to #514

2023-06-26 09:20 UTC, closed without merging