[18913] Expose PayloadPool in DDSDataWriter and DDSDataReader
eProsima/Fast-DDS-docs pull request #514
Opened 2023-06-26 09:18 UTC by JesusPoderoso

Renamed branch name to facilitate CI jobs
This PR closes the previous PR #513 , and changes requested would be applied in this one

2023-06-26 13:22 UTC, JesusPoderoso commented
@richiprosima please test this

2023-06-28 06:38 UTC, EduPonz requested changes

2023-06-28 06:38 UTC, EduPonz commented on code/CustomPayloadPool.hpp
I don't think we need a full implementation, an empty one would suffice since the code does not run. Furthermore, I'd put it inside the scope of the snippet but above the comment for inclusion (so it's no visible on the snippet itself) instead of as a separate header.

2023-07-05 13:58 UTC, EduPonz commented on code/CustomPayloadPool.hpp
The second part of the comment is not taken. I meant move the class to right above [here](https://github.com/eProsima/Fast-DDS-docs/pull/514/files#diff-6b59e80db50243abdf5723fa767ef72d24b97392025a51fe2b183e77f2eff93eR2538)

2023-07-05 15:36 UTC, JesusPoderoso commented on code/CustomPayloadPool.hpp
The snippet code was not able to find the local class defined in that scope. I had to take it off, and move it to the start of the file in order to build successfully.

2023-07-05 20:38 UTC, EduPonz approved these changes

2023-07-24 08:19 UTC, JesusPoderoso commented
[Manual CI](https://github.com/eProsima/Fast-DDS/actions/runs/5642268793) run with Fast DDS public API branch succed

2023-08-03 05:45 UTC, EduPonz approved these changes

2023-08-03 12:00 UTC, merged