[18965] Improved threading model information
eProsima/Fast-DDS-docs pull request #519
Opened 2023-07-03 14:22 UTC by jsantiago-eProsima

Partial rewriting of threading information to include additional information and all threads spawned by Fast DDS, as well as their cardinality and conditions.

2023-07-04 13:37 UTC, EduPonz requested changes

2023-07-04 13:37 UTC, EduPonz commented on docs/fastdds/library_overview/includes/exec_model.rst
> +Security logging and Shared Memory packet logging threads both require certain configuration options to be enabled.
I'd put this as a list here

2023-07-04 13:37 UTC, EduPonz commented on docs/fastdds/library_overview/includes/exec_model.rst
> +      - One per port
Either we link to the default ports somehow (IDK whether we have that) or we elabore further here on the number of ports

2023-07-04 13:37 UTC, EduPonz commented on docs/fastdds/library_overview/includes/exec_model.rst
> +      - Accumulates and writes security log entries.
Missing:

1. The FileWatch threads
1. Discovery Server thread

2023-07-04 13:37 UTC, EduPonz commented on docs/fastdds/library_overview/includes/exec_model.rst
> +        Even for synchronous writers, some forms of communication must be initiated in the background.
I think it's worth stating that by default there is one of these

2023-07-05 07:23 UTC, rsanchez15 requested changes

2023-07-05 07:23 UTC, rsanchez15 commented on docs/fastdds/library_overview/includes/exec_model.rst
> +    * - Name
I'd try to fit the table into the page width

2023-07-05 13:07 UTC, EduPonz commented on docs/fastdds/library_overview/includes/exec_model.rst
> +      - One per port
I don't think this has been addressed

2023-07-05 13:09 UTC, EduPonz commented on docs/fastdds/library_overview/includes/exec_model.rst
> +      - One per port
Nevermind

2023-07-05 13:15 UTC, EduPonz submitted a review, later dismissed

2023-07-05 13:52 UTC, rsanchez15 approved these changes

2023-07-05 15:38 UTC, rsanchez15 approved these changes

2023-07-05 15:38 UTC, merged