[19182] Version 2.11.1 release notes
eProsima/Fast-DDS-docs pull request #528
Opened 2023-07-13 14:04 UTC by jsantiago-eProsima

2023-07-13 14:11 UTC, JesusPoderoso submitted a review, later dismissed
LGTM

2023-07-17 14:21 UTC, MiguelCompany requested changes

2023-07-17 14:21 UTC, MiguelCompany commented on docs/notes/notes.rst
> +    5. Revert parallel testing SemaphoreNode changes
```suggestion
    1. Fixed long-standing reconnection issue on SHM transport
    2. Added missing include
```

2023-07-17 14:21 UTC, MiguelCompany commented on docs/notes/notes.rst
> +    9. Dynamic memory topic payload pool properly handle Zero sized payloads
```suggestion
    9. Properly handle zero-sized payloads on dynamic memory payload pools
```

2023-07-18 05:54 UTC, MiguelCompany approved these changes

2023-07-18 06:09 UTC, merged