[19570] Improve locators documentation
eProsima/Fast-DDS-docs pull request #558
Opened 2023-09-19 11:26 UTC by JesusPoderoso

Fixes #3857

2023-09-20 05:15 UTC, EduPonz requested changes
I think we should take the opportunity also document the WAN address here

2023-09-20 05:15 UTC, EduPonz commented on docs/fastdds/transport/transport_api.rst
> +applications with different ports in the same host.
I did not account for line length.
```suggestion
In TCP, this distinction allows for several DDS applications using different RTPS ports (*logical ports*) to share the same *physical port*, thus only requiring for a single port to be opened for all communications.
```

2023-09-20 05:15 UTC, EduPonz commented on docs/fastdds/transport/transport_api.rst
> +  It is used by the RTPS applications to perform communications.
```suggestion
  It is used by the RTPS protocol to distinguish different entities.
```

2023-09-20 05:36 UTC, JesusPoderoso commented
> I think we should take the opportunity also document the WAN address here

I did not find the wan address in the [locators api](https://fast-dds.docs.eprosima.com/en/latest/fastdds/api_reference/rtps/common/Locator/Locator_t.html), to be referenced as done in the bullet points (`|Locator_t::port-api|` for instance)

2023-09-20 09:54 UTC, EduPonz requested changes

2023-09-20 09:54 UTC, EduPonz commented on docs/fastdds/transport/transport_api.rst
> +* The IPv6 address uses the 16 available Bytes to represent an unique and global address.
```suggestion
* The IPv6 address uses the 16 available bytes to represent a unique and global address.
```

2023-09-20 09:54 UTC, EduPonz commented on docs/fastdds/transport/transport_api.rst
> +* The IPv4 address splits those 16 Bytes in the following three sections, ordered from less to greatest significant:
```suggestion
* The IPv4 address splits those 16 bytes in the following three sections, ordered from least to greatest significance:
```

2023-09-20 09:54 UTC, EduPonz commented on docs/fastdds/transport/transport_api.rst
> +  - 16 Bytes unique LAN identifier: TCP only identifier for the TCP connection.
```suggestion
  - 4 bytes LAN IP: local subnet identification (UDP and TCP).
  - 4 bytes WAN IP: Public IP (TCP only).
  - 8 bytes unused.
```

2023-09-20 09:54 UTC, EduPonz commented on docs/fastdds/transport/transport_api.rst
> +    TODO Edu choose which representation fits better in the documentation
This one please, but with the header separately

2023-09-20 09:54 UTC, EduPonz commented on docs/fastdds/transport/transport_api.rst
> +address.
I'd rather say something in the lines of WAN address manipulation, the link is alright

2023-09-20 09:54 UTC, EduPonz commented on docs/fastdds/transport/transport_api.rst
> +    | Unique LAN ID (192.168.1.1.1.1.2.55) | WAN address (62.128.41.210) | LAN address (192.168.0.113) |
Please add formatting
```suggestion
    | Unused | WAN address (62.128.41.210) | LAN address (192.168.0.113) |
```

2023-09-29 08:50 UTC, EduPonz submitted a review, later dismissed
LGTM with green CI

2023-09-29 09:24 UTC, EduPonz commented
@richiprosima please test this

2023-09-29 09:45 UTC, EduPonz approved these changes

2023-09-29 09:45 UTC, merged