[19730] Add is_sample_valid() checks, references and emphasize
eProsima/Fast-DDS-docs pull request #584
Opened 2023-10-19 14:17 UTC by Mario-DL

This PR corrects the code snippets where loans API was used to include the check for `is_sample_valid()`. It also adds references to the explanation, which, in turn, it has been emphasized.

If approved, we may need to backport to 2.11.x 2.10.x 2.6.x

2023-10-20 06:01 UTC, MiguelCompany requested changes

2023-10-20 06:01 UTC, MiguelCompany commented on code/DDSCodeTester.cpp
> +                    // Only samples for which valid_data is true and sample was not replaced should be accessed
```suggestion
                    // Only samples with valid data should be accessed
```

2023-10-20 06:01 UTC, MiguelCompany commented on code/DDSCodeTester.cpp
> +                                    // Only samples for which valid_data is true and sample was not replaced should be accessed
```suggestion
                                    // Only samples with valid data should be accessed
```

2023-10-20 09:18 UTC, Mario-DL commented on docs/fastdds/dds_layer/subscriber/dataReader/readingData.rst
> +indicate that valid data is present and the sample is valid (i.e, not replaced,
Should we also mention that its important to check also in `intraprocess` ?

2023-10-20 09:29 UTC, MiguelCompany commented on docs/fastdds/dds_layer/subscriber/dataReader/readingData.rst
> +indicate that valid data is present and the sample is valid (i.e, not replaced,
No. If you are not using data sharing, the payload will never be overwritten.

2023-10-20 09:30 UTC, MiguelCompany approved these changes

2023-10-23 08:08 UTC, MiguelCompany commented
@mergifyio backport 2.11.x 2.10.x 2.6.x

2023-10-23 08:08 UTC, merged