[19780] Add interface whitelist by name
eProsima/Fast-DDS-docs pull request #591
Opened 2023-11-07 14:00 UTC by elianalf

The feature gives users the possibility to add network interfaces to the whitelist by interface name as well, not just by their IP address.

Merge after:
- https://github.com/eProsima/Fast-DDS/pull/3973

2023-11-08 09:10 UTC, juanlofer-eprosima requested changes

2023-11-08 09:10 UTC, juanlofer-eprosima commented on docs/fastdds/transport/whitelist.rst
> +  The values in this list should match the IP addresses or interface names on your machine for the corresponding networks. If none of the values in the whitelist match the interfaces on your machine,
```suggestion
  If none of the values in the transport descriptor's whitelist match the interfaces on your machine, all the interfaces in the whitelist are filtered out and no communication will be established through that transport.
```

2023-11-08 09:10 UTC, juanlofer-eprosima commented on docs/fastdds/transport/whitelist.rst
> +  The values in this list should match the IP addresses or interface names on your machine for the corresponding networks. If none of the values in the whitelist match the interfaces on your machine,
Just to shorten it a bit, and saying we add an invalid ip is perhaps too low level for a user.

2023-11-08 13:12 UTC, juanlofer-eprosima submitted a review, later dismissed
LGTM

2023-11-09 19:43 UTC, EduPonz requested changes
A couple of NITs

2023-11-09 19:43 UTC, EduPonz commented on docs/fastdds/transport/whitelist.rst
> +or the interface names.
```suggestion
The interfaces in |SocketTransportDescriptor::interfaceWhiteList-api| can be specified both by IP address
or interface name.
```

2023-11-09 19:43 UTC, EduPonz commented on docs/fastdds/transport/whitelist.rst
> +
Indent the tabs so they are nested withing the bullet list

2023-11-09 19:43 UTC, EduPonz commented on docs/fastdds/transport/whitelist.rst
> +.. tabs::
Same as before, indent the tabs

2023-11-09 19:43 UTC, EduPonz commented on docs/fastdds/transport/whitelist.rst
> +  all the interfaces in the whitelist are filtered out and no communication will be established through that transport.
```suggestion
  If none of the values in the transport descriptor's whitelist matches the interfaces present on the host,
  then all the interfaces in the whitelist are filtered out and therefore no communication will be established through that transport.
```

2023-11-10 10:04 UTC, EduPonz submitted a review, later dismissed
LGTM with green CI

2023-11-10 10:29 UTC, EduPonz approved these changes
LGTM with green CI

2023-11-23 14:32 UTC, EduPonz commented
@mergifyio rebase master

2023-12-05 13:36 UTC, merged