[20021]  TCP support for Discovery server CLI and env var and example
eProsima/Fast-DDS-docs pull request #599
Opened 2023-12-04 13:24 UTC by cferreiragonz

This PR adds documentation for the new TCP features of Discovery Server CLI and the environment variable.

It also adds an example of use that uses TCP along Discovery Server

Merfe after:
- *Pending* (PR)

2023-12-05 14:23 UTC, elianalf requested changes

2023-12-05 14:23 UTC, elianalf commented on docs/fastdds/env_vars/env_vars.rst
Have a look to the first ´important´ section in this paragraph, it may be needed to add also the prefix ´TCPv4´ and ´TCPv6´

2023-12-05 14:23 UTC, elianalf commented on docs/fastdds/use_cases/tcp/tcp_with_discovery_server.rst
> +
In this example the port is automatically assigned so it's different from the previous one, I would suggest to add a description of what the example does (as made for the previous one, "the example can be used to configure a client automatically set the port using TCP communication and connecting to a server on 192.168.10.57 and port 12345 ")

2023-12-12 10:05 UTC, cferreiragonz commented
@richiprosima please test docs

2023-12-13 06:51 UTC, EduPonz commented
@mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

2023-12-13 07:13 UTC, elianalf approved these changes

2023-12-14 07:38 UTC, merged