[20086] Methods to configure transport scenarios Documentation
eProsima/Fast-DDS-docs pull request #619
Opened 2023-12-14 11:20 UTC by cferreiragonz

This PR adds documentation regarding the new Builtin Transports configuration options.
It includes information about:
-New API
-New environment variable
-New XML configuration
-Modifies old cases of uses

Merge after:
- https://github.com/eProsima/Fast-DDS/pull/4098

2023-12-15 08:20 UTC, cferreiragonz commented
@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

2023-12-19 11:04 UTC, EduPonz requested changes
Congrats, this documentation is very well written!

2023-12-19 11:04 UTC, EduPonz commented on docs/fastdds/transport/tcp/tcp.rst
> +transports. There exist two different configurations that enable TCP transports: ``LARGE_DATA`` and ``LARGE_DATAv6``.
Remove large data v6 from here

2023-12-19 11:04 UTC, EduPonz commented on docs/fastdds/transport/tcp/tcp.rst
> +during the participant discovery phase (see :ref:`disc_phases`) while the application data delivery occurs over TCP
Again, not exactly

2023-12-19 11:04 UTC, EduPonz commented on code/DDSCodeTester.cpp
> +
```suggestion
```

2023-12-19 14:38 UTC, EduPonz approved these changes

2023-12-19 15:18 UTC, merged