Bump version to v2.10.3
eProsima/Fast-DDS-docs pull request #622
Opened 2023-12-15 11:15 UTC by elianalf

2024-01-18 07:21 UTC, JesusPoderoso commented
@richiprosima please test this

2024-01-18 14:34 UTC, EduPonz requested changes

2024-01-18 14:34 UTC, EduPonz commented on docs/notes/notes.rst
Please update with the latest version of Fast DDS release notes

2024-01-31 15:14 UTC, EduPonz approved these changes

2024-01-31 15:20 UTC, merged