[20176] Bump version to v2.13.1
eProsima/Fast-DDS-docs pull request #634
Opened 2023-12-22 12:25 UTC by MiguelCompany

Bump version and release notes

2023-12-22 12:29 UTC, cferreiragonz approved these changes

2024-01-11 07:07 UTC, JesusPoderoso requested changes

2024-01-11 07:07 UTC, JesusPoderoso commented on docs/notes/notes.rst
Include latest  merged PRs
```suggestion
3. Fix data race when processing incoming PDP samples on different threads.
4. Fix DNS test filter in CMakeLists
5. Downgrade CMake minimum required version to 3.20
6. Update versions.md
7. Update PR template to include check for PR description, title and backports
8. Update Fast CDR submodule to v2.1.3

```

2024-01-11 07:19 UTC, MiguelCompany commented on docs/notes/notes.rst
666c8ce

2024-01-11 07:27 UTC, JesusPoderoso approved these changes
LGTM

2024-01-11 09:06 UTC, JesusPoderoso approved these changes
LGTM

2024-01-11 10:47 UTC, merged