[20119] TCP socket send buffer limit
eProsima/Fast-DDS-docs pull request #646
Opened 2024-01-16 14:58 UTC by jepemi

Add non_blocking_send to TCPTransportDescriptor.

Merge after:

- https://github.com/eProsima/Fast-DDS/pull/4237

2024-01-23 16:01 UTC, MiguelCompany requested changes

2024-01-23 16:01 UTC, MiguelCompany commented on docs/fastdds/rtps_layer/rtps_layer.rst
> +     * |TransportInterface-api| ``non_blocking_send`` is set to true.
Change the link to the new section in non-consolidated qos

2024-01-24 08:50 UTC, MiguelCompany approved these changes

2024-02-06 07:54 UTC, merged

2024-02-06 07:54 UTC, EduPonz commented
@jepemi please order backports here

2024-02-14 19:35 UTC, EduPonz commented on docs/fastdds/rtps_layer/rtps_layer.rst
> +     * :ref:`property_policies_tcp_non_blocking_send` is set to true.
I don't think this is true anymore