[20401] Improve History QoS documentation and compatibility rules
eProsima/Fast-DDS-docs pull request #664
Opened 2024-02-14 10:02 UTC by JesusPoderoso

This PR follows improves the History QoS configuration documentation and give some extra light regarding specific scenarios and compatibility with other QoS.

**Note**: This PR also updates the code / XML examples to the latest style followed in the documentation, as in continuous improvement.

Fast DDS related PR: 
- https://github.com/eProsima/Fast-DDS/pull/4375

2024-02-15 07:14 UTC, Mario-DL requested changes
Nice docs inclusions. Also, thanks for refactoring the C++ code tester examples in the file to the latest format.
I left some NITs and a couple of suggestions.

2024-02-15 07:14 UTC, Mario-DL commented on docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> +        :end-before: //!
NIT space
```suggestion
       :language: c++
       :dedent: 8
       :start-after: //DDS_CHANGE_TOPIC_DATA_QOS_POLICY
       :end-before: //!
```

2024-02-15 07:14 UTC, Mario-DL commented on docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> +        :end-before: <!--><-->
```suggestion
       :language: xml
       :start-after: <!-->XML_CHANGE_TOPIC_DATA_QOS_POLICY
       :end-before: <!--><-->
```

2024-02-15 07:14 UTC, Mario-DL commented on docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> +        :end-before: //!
```suggestion
       :language: c++
       :dedent: 8
       :start-after: //DDS_CHANGE_USER_DATA_QOS_POLICY
       :end-before: //!
```

2024-02-15 07:14 UTC, Mario-DL commented on docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> +        :end-before: <!--><-->
```suggestion
       :language: xml
       :start-after: <!-->XML_CHANGE_USER_DATA_QOS_POLICY
       :end-before: <!--><-->
```

2024-02-15 07:14 UTC, Mario-DL commented on docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> +* The |HistoryQosPolicy::depth-api| cannot be zero.
We may start here stating that the `depth` is only taken into consideration when `kind` is `KEEP_LAST`. Also, when we finally agree on the `Fast DDS's PR` how we manage having a LENGTH_UNLIMITED, we update it here.

2024-02-15 07:14 UTC, Mario-DL commented on docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> +  the first one will block the DataWriter when maximum :ref:`resourcelimitsqospolicy` settings reached, but the second
```suggestion
  the first one will block the DataWriter when maximum :ref:`resourcelimitsqospolicy` settings are reached, but the second
```

2024-02-15 07:14 UTC, Mario-DL commented on docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> +        :end-before: //!
NIT spacing
```suggestion
       :language: c++
       :dedent: 8
       :start-after: //DDS_CHANGE_GROUP_DATA_QOS_POLICY
       :end-before: //!
```

2024-02-15 07:14 UTC, Mario-DL commented on docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> +        :end-before: <!--><-->
```suggestion
       :language: xml
       :start-after: <!-->XML_CHANGE_GROUP_DATA_QOS_POLICY
       :end-before: <!--><-->
```

2024-02-15 07:14 UTC, Mario-DL commented on docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> +  one will discard the oldest samples when the depth is reached.
NIT
```suggestion
  one will discard the oldest samples when the |HistoryQosPolicy::depth-api| is reached.
```

2024-02-19 08:22 UTC, Mario-DL commented on docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> +* The |HistoryQosPolicy::depth-api| cannot be zero.
Finally, we should state here that `depth` cannot be less or equal than 0.

2024-02-19 13:23 UTC, Mario-DL commented on docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
> +    Those oldest samples may belong to other :ref:`instances<dds_layer_topic_instances>`.
NIT
```suggestion
    Those oldest samples may belong to different :ref:`instances<dds_layer_topic_instances>`.
```

2024-02-20 08:18 UTC, Mario-DL approved these changes
LGTM with green CI

2024-02-20 13:34 UTC, merged

2024-02-20 13:34 UTC, EduPonz commented
@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x