Improve LARGE_DATA documentation
eProsima/Fast-DDS-docs pull request #671
Opened 2024-02-19 11:21 UTC by cferreiragonz

This PR adds a note recommending the manual configuration of the send and receive buffer sizes when using the LARGE_DATA mode. It also extends the current documentation regarding LARGE_DATA mode in the _Use Cases_ and the _TCP Transport_ sections to include the environment variable option.

2024-02-20 08:26 UTC, rsanchez15 requested changes

2024-02-20 08:26 UTC, rsanchez15 commented on docs/fastdds/rtps_layer/rtps_layer.rst
> +  To obtain a better performance when working with large data messages it is extremely recommended to set through
Add it as a separate warning.

2024-02-20 08:26 UTC, rsanchez15 commented on docs/fastdds/troubleshooting/troubleshooting.rst
> +* Although Fast DDS' UDP default transport is designed to work in most network environments, it may encounter certain
```suggestion
* Although UDP/SHM default transports of Fast DDS are designed to work in most network environments, they may encounter certain
```

2024-02-20 08:26 UTC, rsanchez15 commented on docs/fastdds/troubleshooting/troubleshooting.rst
> +  or via code. For more information, please refer to :ref:`use-case-tcp-multicast`.
```suggestion
  limitations when operating over WiFi or within lossy network conditions. In these cases, it is advisable to set up
  the ``LARGE_DATA`` configuration, which has been specifically optimized for these scenarios. The ``LARGE_DATA`` profile
  limits the use of UDP solely to the :ref:`PDP discovery<disc_phases>` phase, employing the more reliable TCP/SHM for
  the remainder of the communication process. Its implementation can be accomplished by simply configuring the
  ``FASTDDS_BUILTIN_TRANSPORTS`` environment variable, or alternatively through XML profiles
  or via code. For more information, please refer to :ref:`use-case-tcp-multicast`.
```

2024-02-20 08:26 UTC, rsanchez15 commented on docs/fastdds/use_cases/tcp/tcp_with_multicast_discovery.rst
>  .. note::
Adding the comment here as I cannot add it in the code-block below. 

I'd add the code-block in the note. If this is not possible add another section with the note and the code just for stating how to disable SHM

2024-02-20 09:51 UTC, rsanchez15 approved these changes

2024-02-20 13:05 UTC, merged

2024-03-01 07:27 UTC, cferreiragonz commented
@Mergifyio backport 2.13.x 2.12.x 2.10.x 2.6.x

2024-03-01 07:34 UTC, cferreiragonz commented
@Mergifyio backport 2.13.x