[20439] Authentication Handshake Properties documentation
eProsima/Fast-DDS-docs pull request #681
Opened 2024-02-22 17:29 UTC by Mario-DL

This PR ads the documentation for configuring the `Authentication Handshake` behavior through the following properties:
* `max_handshake_requests`
* `initial_handshake_resend_period`
* `handshake_resend_period_gain`

2024-02-23 08:44 UTC, Mario-DL commented
@richiprosima please test docs

2024-02-26 14:10 UTC, elianalf requested changes
It would be nice if there was a reference to the new page `Security Plugin Settings` at the end of the section [8. Security](https://eprosima-fast-rtps--681.org.readthedocs.build/en/681/fastdds/security/security.html) so it can be easly found

2024-02-26 14:10 UTC, elianalf commented on docs/fastdds/property_policies/security.rst
> +The DDS\:Logging\:DDS_LogTopic authentication plugin, can be activated setting the |DomainParticipantQos|
```suggestion
The :ref:`DDS\:Logging\:DDS_LogTopic <logging-logtopic>` authentication plugin, can be activated setting the |DomainParticipantQos|
```

2024-02-26 17:11 UTC, Mario-DL commented
> Everything is clear! It would be nice if there was a reference to the new page `Security Plugin Settings` at the end of the section [8. Security](https://eprosima-fast-rtps--681.org.readthedocs.build/en/681/fastdds/security/security.html) so it can be easly found

Good one !

2024-02-26 21:11 UTC, Mario-DL commented
@richiprosima please test docs

2024-02-26 21:59 UTC, Mario-DL commented
@richiprosima please test docs

2024-02-27 06:58 UTC, Mario-DL commented
@richiprosima please test docs

2024-02-27 07:33 UTC, Mario-DL commented
@richiprosima please test docs

2024-02-28 07:09 UTC, elianalf approved these changes

2024-03-01 06:52 UTC, merged

2024-03-01 07:19 UTC, JesusPoderoso commented
@Mergifyio backport 2.13.x 2.12.x 2.10.x 2.6.x