[20825] Bump version to v2.6.8
eProsima/Fast-DDS-docs pull request #749
Opened 2024-04-23 08:59 UTC by Mario-DL

## Description

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [ ] Code snippets related to the added documentation have been provided.
- [ ] Documentation tests pass locally.
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] CI passes without warnings or errors.

2024-04-23 09:00 UTC, Mario-DL commented
@richiprosima please test docs

2024-04-23 09:18 UTC, Mario-DL commented
@richiprosima please test docs

2024-04-23 11:01 UTC, Mario-DL commented
@richiprosima please test docs

2024-04-23 20:47 UTC, JesusPoderoso requested changes

2024-04-23 20:47 UTC, JesusPoderoso commented on docs/notes/notes.rst
> +#. Add macOS and Ubuntu Github CI.
I would set this features as GitHub CI improvement

2024-04-23 20:47 UTC, JesusPoderoso commented on docs/notes/notes.rst
> +#. Build Fast DDS Python bindings in Fast DDS Docs Github CI job.
This would be a GitHub CI improvement, as well as the one shapes demo related

2024-04-24 10:09 UTC, JesusPoderoso approved these changes
LGTM

2024-04-25 13:16 UTC, merged