[21054] Add XML configuration for FlowControllerDescriptor
eProsima/Fast-DDS-docs pull request #782
Opened 2024-05-24 09:57 UTC by Mario-DL

## Description

This PR adds the XML configuration for FlowControllerDescriptor.

Related implementation PR:
* eProsima/Fast-DDS#4837

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] Code snippets related to the added documentation have been provided.
- [X] Documentation tests pass locally.
- __NO__ Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] CI passes without warnings or errors.

2024-05-24 10:09 UTC, Mario-DL commented
@richiprosima please test_3 this

2024-05-27 08:12 UTC, Mario-DL commented on docs/fastdds/use_cases/large_data/large_data.rst
> +         :end-before: <!--><-->
Totally agree, nice catch !

2024-05-27 08:30 UTC, JesusPoderoso approved these changes
LGTM

2024-05-27 12:53 UTC, JesusPoderoso commented
@richiprosima please test_3 this

2024-05-27 13:22 UTC, JesusPoderoso requested changes

2024-05-27 13:22 UTC, JesusPoderoso commented on docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
> +
Linter complaints about line too long
```suggestion
Also, the |PublishModeQosPolicy::flow_ctrl_name-api| has to be set to the name of a valid :ref:`flow-controllers` 
descriptor name.

```

2024-05-27 13:37 UTC, JesusPoderoso approved these changes

2024-05-27 13:37 UTC, JesusPoderoso commented
@richiprosima please test_3 this

2024-05-31 10:42 UTC, merged