[21054] Make explicit the need to keep alive the flow controller descriptor name
eProsima/Fast-DDS-docs pull request #806
Opened 2024-06-07 07:25 UTC by Mario-DL

## Description

**Important** This PR has to be cherry picked on the following backports:
* #802 
* #803 
* #804

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] Code snippets related to the added documentation have been provided.
- [X] Documentation tests pass locally.
- __NO__ (see PR description) Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] CI passes without warnings or errors.

2024-06-07 09:04 UTC, MiguelCompany requested changes

2024-06-07 09:04 UTC, MiguelCompany commented on code/DDSCodeTester.cpp
> +        static std::string flow_controller_name{"example_flow_controller"}
```suggestion
        static std::string flow_controller_name{"example_flow_controller"};
```

2024-06-07 09:49 UTC, JesusPoderoso commented
@richiprosima please  test this

2024-06-08 05:49 UTC, EduPonz requested changes

2024-06-08 05:49 UTC, EduPonz commented on code/DDSCodeTester.cpp
> +        //Important: the flow_controller_name must be kept alive during the Participant's lifetime.
```suggestion
        // Important: the flow_controller_name must be kept alive during the Participant's lifetime.
```

2024-06-08 05:49 UTC, EduPonz commented on code/DDSCodeTester.cpp
> +        //Important: the flow_controller_name must be kept alive during the Participant's lifetime.
```suggestion
        // Important: the flow_controller_name must be kept alive during the Participant's lifetime.
```

2024-06-08 05:50 UTC, merged

2024-06-08 05:50 UTC, EduPonz commented
@Mario-DL please remember to cherry-pick this onto the other backports