[21137] Adapt to RTPS WriterHistory refactor
eProsima/Fast-DDS-docs pull request #826
Opened 2024-06-26 10:30 UTC by MiguelCompany

## Description

This PR adapts the RTPS example code for the refactor in `WriterHistory`.

Related implementation PR:
* eProsima/Fast-DDS#4966

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] Code snippets related to the added documentation have been provided.
- [ ] Documentation tests pass locally.
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] CI passes without warnings or errors.

2024-06-26 10:31 UTC, MiguelCompany commented
@richiprosima Please test_3 docs

2024-06-26 11:19 UTC, EduPonz requested changes
NIT

2024-06-26 11:19 UTC, EduPonz commented on code/CodeTester.cpp
> +    //Request a change from the history
NIT: can you please add a space after `//` in this snippet's comments?

2024-06-27 08:12 UTC, EduPonz commented
@richiprosima Please test_3 docs

2024-06-27 13:22 UTC, merged