[21244] Bump version to v2.6.9
eProsima/Fast-DDS-docs pull request #843
Opened 2024-07-03 09:57 UTC by Mario-DL

## Description

This PR bumps `Fast DDS docs` version to `v2.6.9`

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- __NO__ Code snippets related to the added documentation have been provided.
- __NO__ Documentation tests pass locally.
- __NO__ Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] CI passes without warnings or errors.

2024-07-03 13:31 UTC, elianalf requested changes

2024-07-03 13:31 UTC, elianalf commented on docs/notes/notes.rst
We shell add a comment related to the fact that from now on it will be security fixes only

2024-07-04 09:26 UTC, elianalf approved these changes

2024-07-04 12:57 UTC, JesusPoderoso requested changes

2024-07-04 12:57 UTC, JesusPoderoso commented on docs/notes/notes.rst
>  =============
```suggestion
Version 2.6.9 (maintenance)
===========================
```

2024-07-04 12:59 UTC, JesusPoderoso approved these changes

2024-07-04 13:18 UTC, merged