[21783] Add notes for Fast DDS `v3.1.0`
eProsima/Fast-DDS-docs pull request #930
Opened 2024-10-10 14:26 UTC by Mario-DL

## Description

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- **N/A** Code snippets related to the added documentation have been provided.
- [ ] Documentation tests pass locally.
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] CI passes without warnings or errors.

2024-10-10 14:48 UTC, JesusPoderoso requested changes
We forgot to update the Dependencies and compatibilities section in the Bump to 3.1.x with the new tabs.
I think we should include it in this PR, together with the new versions of CDR, Gen and Shapes

2024-10-10 14:48 UTC, JesusPoderoso commented on docs/notes/previous_versions/v3.1.0.rst
> +#. Convert ``Fast DDS v2`` to ``v3`` Migration Changes into a Step-by-Step User Guide
I would add a link in the migration guide section and add a reference to the section here
```suggestion
#. Convert ``Fast DDS v2`` to ``v3`` Migration Changes into a :ref:`Step-by-Step User Guide <migration_guide>`.
```

2024-10-10 14:48 UTC, JesusPoderoso commented on docs/notes/previous_versions/v3.1.0.rst
> +#. Add QoS getters from raw ``XML``
Can we add any documentation reference here?

2024-10-11 08:36 UTC, Mario-DL commented on docs/notes/previous_versions/v3.1.0.rst
> +    But it is advisable to regenerate them using the latest patch version of ``Fast DDS-Gen v4.0.x``.
Okay, we mention that it is advisable to use the latest patch version, but I aggree that it is more complete to state directly the minimum to `2`

2024-10-11 10:00 UTC, JesusPoderoso approved these changes
LGTM

2024-10-11 10:11 UTC, merged